version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo POST BUILDING...
artifacts: 
  files:
    - 'dist/**/*'
    - appspec.yml
    - scripts/*

